### PR TITLE
Fix infinite loop while analysing project targets

### PR DESCRIPTION
**Pull request by kraktus**
When trying to debug https://github.com/dnlmlr/cargo-clean-all/issues/13

I found that the repo would hang while trying to get the size of the target of this project https://github.com/kraktus/test-raw-ffi.

By debugging it seems that `ProjectTargetAnalysis::recursive_scan_target` is caught in an infinite loop (while `$ du -sh` works fine), seemingly due to symlinks in the targets dir, generated by the `cxx` crate for FFI.

I replaced the manual recursive scan with `walkdir`, an established crate, which does not follow symlinks by default, and the issue vanished.

### CODE REVIEW

**Comment by dnlmlr** [comment]
Hey again and thanks for the PR! Unfortunately I have too much stuff to do over the next few days to look into this in more detail (which I would still like to do before merging the PR). I should find time to do that around thursday or friday. 

That being said, your point about symlinks sounds like it could indeed be an issue and create infinite loops. That is definitely something that needs to be fixed. Maybe it should default to not following symlinks at all and make that feature optional.

**Comment by kraktus** [comment]
Sure, there's no hurry I used my fork locally. I've made a couple of other patches that might be useful, will post them later.

**Comment by dnlmlr** [comment]
So I started looking into this and it seems that this issue, or at least its potential, was already discovered and fixed in #12 for the main target dir scan:
> The file types returned by read_dir don't follow symbolic links. So whereas Path::is_dir would return true if the path was a symbolic link to a directory, the file_type of the directory entry would be a symbolic link, so would return false to is_dir. This means that this change prevents the tool from following symbolic links. Following symbolic links can lead to processing of parts of the filesystem that the user didn't intend and can also lead to effectively running forever if a symbolic link leads to a parent directory (as is the case if you have a rustc build directory lying around).

Your suggested change certainly fixes the issue since walkdir doesn't follow symlinks by default. That being said, the issue is extremely easy to fix without pulling in a new dependency by just checking for symlinks in the `recursive_scan_target` function.

So thanks a lot for bringing up the issue and suggesting a fix, but I'll close this particular PR and add the check to the existing code instead

**Comment by kraktus** [comment]
Hey, I can confirm this fixes for me too, thanks!

**Pull request closed without merging**
